version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: certificadosdb
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: certificados-backend
    restart: always
    ports:
      - "3010:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/certificadosdb
      NODE_ENV: production
    depends_on:
      - mongo
    volumes:
      - ./storage:/usr/src/app/storage

volumes:
  mongo_data:
